---
ansible_python_interpreter: /usr/bin/python3
debug: false

firewalld_default:
  public:
    interfaces: [eth0, eth1]
    add_ports: ['{{ glpi_agent_port }}/tcp']
    add_services: [ssh]
    remove_services: [dhcpv6-client, cockpit]

rsyslog_elasticsearch_server: '{{ hostvars["logs"].ip }}:9200'
rsyslog_elasticsearch_user: rsyslog
rsyslog_elasticsearch_password: '{{ lookup("ansible.builtin.password",
  opensearch_rsyslog_password_file, length=26) }}'
rsyslog_rules_add: []
rsyslog_rules_default: [audit, syslog]

tls_gen_cert_domain: otus.abegorov.ru
tls_gen_cert_san:
  - 'DNS:{{ inventory_hostname_short }}.{{ tls_gen_cert_domain }}'
  - 'DNS:localhost'
  - 'IP:{{ ip }}'
  - 'IP:127.0.0.1'
tls_ca: '{{ lookup("ansible.builtin.file", "secrets/certs/CA.crt") }}'
tls_key: '{{ lookup("ansible.builtin.file", "secrets/certs/" +
  inventory_hostname + ".key") }}'
tls_cert: '{{ lookup("ansible.builtin.file", "secrets/certs/" +
  inventory_hostname + ".crt") }}'
tls_full: |
  {{ tls_cert }}
  {{ tls_ca }}
trust_ca_certs:
  LOCAL ROOT CA: '{{ tls_ca }}'

angie_certs:
  - name: '{{ inventory_hostname }}'
    key: '{{ tls_key }}'
    cert: '{{ tls_full }}'
angie_passwd:
  metrics:
    - name: '{{ metrics_user }}'
      password: '{{ metrics_password }}'
angie_metrics_listen: ['{{ ip }}:{{ angie_metrics_port }}']
angie_metrics_port: 9913

glpi_server_name: glpi.otus.abegorov.ru

glpi_uid: 60000
glpi_gid: 60000
glpi_db_user: glpi
glpi_db_password: '{{ lookup("ansible.builtin.password",
  "secrets/mariadb_glpi_password.txt", length=26) }}'
glpi_db_name: glpi
glpi_servers: '{{ hostvars | ansible.builtin.dict2items |
  selectattr("key", "in", groups["backend"]) | map(attribute="value") |
  map(attribute="ip") }}'

glpi_agent_server: '{{ ["https://"] | ansible.builtin.product(glpi_servers) |
  map("join") | join(",") }}'
glpi_agent_httpd_ip: '{{ ip }}'
glpi_agent_port: 62354

opensearch_rsyslog_password_file: "secrets/opensearch_rsyslog_password.txt"

metrics_user: metrics
metrics_password: '{{ lookup("ansible.builtin.password",
  "secrets/metrics_password.txt", length=26) }}'
...
