---
ansible_python_interpreter: /usr/bin/python3
debug: true

glpi_db_user: glpi
glpi_db_password: '{{ lookup("ansible.builtin.password",
  "secrets/mariadb_glpi_password.txt", length=26) }}'
glpi_db_name: glpi
...
