---
prometheus_labels:
  group: 'backend'

angie_sites: [http_to_https, glpi, metrics]
angie_set_real_ip_from: ['{{ hostvars["frontend"].ip }}']
angie_http_to_https_listen: ['{{ ip }}:80']
angie_glpi_listen: ['{{ ip }}:443']
angie_glpi_server_name: '{{ glpi_server_name }}'

firewalld_override:
  public:
    add_ports: ['{{ angie_metrics_port }}/tcp']
    add_services: [http, https]

rsyslog_rules_add: [glpi, nginx]

glpi_var_dir: /var/lib/glpi
glpi_config_dir: /etc/glpi
glpi_db_host: '{{ hostvars["primary"].ip }}'
glpi_db_replica: '{{ hostvars["replica"].ip }}'
glpi_db_ca: '{{ tls_ca }}'
glpi_db_cert: '{{ tls_cert }}'
glpi_db_key: '{{ tls_key }}'

nfs_automount_mount: '{{ glpi_var_dir }}'
nfs_automount_host: '{{ hostvars["nfs"].ip }}'
nfs_automount_path: /glpi
nfs_automount_options: context="system_u:object_r:httpd_var_lib_t:s0"
...
