---
angie_sites: [glpi]
angie_glpi_server_name: '{{ glpi_server_name }}'

firewalld_override:
  public:
    add_services: [http, https]

glpi_var_dir: /var/lib/glpi

nfs_automount_mount: '{{ glpi_var_dir }}'
nfs_automount_host: '{{ hostvars["nfs"].ip }}'
nfs_automount_path: /glpi
nfs_automount_options: context="system_u:object_r:httpd_var_lib_t:s0"
...
