---
prometheus_labels:
  group: 'mariadb'

firewalld_override:
  public:
    add_ports: ['9104/tcp']
    add_services: [mysql]

mariadb_tls_dir: /etc/mariadb/certs
mariadb_tls_ca: '{{ tls_ca }}'
mariadb_tls_cafile: '{{ mariadb_tls_dir }}/ca.crt'
mariadb_tls_cert: '{{ tls_cert }}'
mariadb_tls_certfile: '{{ mariadb_tls_dir }}/server.crt'
mariadb_tls_key: '{{ tls_key }}'
mariadb_tls_keyfile: '{{ mariadb_tls_dir }}/server.key'

mariadb_replication_user: replication
mariadb_replication_password: '{{ lookup("ansible.builtin.password",
  "secrets/mariadb_replication_password.txt", length=26) }}'
mariadb_exporter_user: exporter
mariadb_exporter_password: '{{ lookup("ansible.builtin.password",
  "secrets/mariadb_exporter_password.txt", length=26) }}'

ssh_authorized_keys_users_files:
  root: ['secrets/root@backup.pub']

mariadb_restore_delegate_to: backup

mysqld_exporter_cert: '{{ tls_full }}'
mysqld_exporter_key: '{{ tls_key }}'
mysqld_exporter_db_host: '127.0.0.1'
mysqld_exporter_db_user: '{{ mariadb_exporter_user }}'
mysqld_exporter_db_password: '{{ mariadb_exporter_password }}'
mysqld_exporter_db_ca: '{{ tls_ca }}'
mysqld_exporter_db_cert: '{{ tls_cert }}'
mysqld_exporter_db_key: '{{ tls_key }}'
mysqld_exporter_listen: '{{ prometheus_ip }}:9104'
mysqld_exporter_user: '{{ metrics_user }}'
mysqld_exporter_password_hash: '{{ metrics_password_hash }}'
...
