---
glpi_version: '10.0.17'
glpi_archive_name: glpi-{{ glpi_version }}.tgz
glpi_download_url: https://github.com/glpi-project/glpi/releases/download/{{
  glpi_version }}/{{ glpi_archive_name }}
glpi_download_checksum: >-
  sha256:4cfc485ad2b1ba16e38d2725a13375bda784abf1533a79971711feed0a7f5e11

glpi_uid: 60000
glpi_gid: 60000
glpi_fpm_listen_acl_users: angie

glpi_dir: /usr/share/glpi
glpi_cache_dir: /var/cache/glpi
glpi_config_dir: /etc/glpi
glpi_log_dir: /var/log/glpi
glpi_var_dir: /var/lib/glpi

glpi_crypt_key_file: secrets/glpicrypt.key
glpi_db_host: '{{ undef() }}'
glpi_db_replica: '{{ undef() }}'
glpi_db_user: glpi
glpi_db_password: '{{ undef() }}'
glpi_db_name: glpi
glpi_db_ca:
glpi_db_cafile: '{{ glpi_config_dir }}/ca.crt'
glpi_db_cert:
glpi_db_certfile: '{{ glpi_config_dir }}/client.crt'
glpi_db_key:
glpi_db_keyfile: '{{ glpi_config_dir }}/client.key'
...
