---
- name: Common provision
  tags: common
  hosts: all
  become: true
  gather_facts: false
  roles:
    - firewalld
    - tls_gen
    - trust_ca
    - epel_release
    - glpi_agent

- name: Backup provision
  tags: backup
  hosts: [backup]
  become: true
  gather_facts: false
  roles:
    - ssh_key
    - ssh_known_hosts

- name: DB provision
  tags: db
  hosts: [mariadb]
  become: true
  gather_facts: false
  roles:
    - mariadb_install
    - ssh_authorized_keys
    - mariadb_status
    - mariadb_restore
    - mariadb_tls
    - mariadb_config
    - mariadb_databases
    - mariadb_users
    - mariadb_replica

- name: NFS server provision
  tags: nfs
  hosts: [nfs]
  become: true
  gather_facts: false
  roles:
    - nfs_server

- name: Frontend and backed provision
  tags: web
  hosts: [frontend, backend]
  become: true
  gather_facts: false
  roles:
    - angie

- name: Backend provision
  tags: backend
  hosts: [backend]
  become: true
  gather_facts: false
  roles:
    - nfs_automount
    - glpi
