groups:

- name: NginxVTS

  rules:

    - alert: NginxHighHttp4xxErrorRate
      expr: 'rate(nginx_vts_server_requests_total{host="*", code="4xx"}[1m]) > 0'
      for: 0m
      labels:
        severity: critical
      annotations:
        summary: Nginx high HTTP 4xx error rate (instance {{ $labels.instance }})
        description: "Too many HTTP requests with status 4xx (> 0)\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"

    - alert: NginxHighHttp5xxErrorRate
      expr: 'rate(nginx_vts_server_requests_total{host="*", code="5xx"}[1m]) > 0'
      for: 0m
      labels:
        severity: critical
      annotations:
        summary: Nginx high HTTP 5xx error rate (instance {{ $labels.instance }})
        description: "Too many HTTP requests with status 5xx (> 0)\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"

    - alert: NginxLatencyHigh
      expr: 'histogram_quantile(0.99, sum(rate(nginx_vts_server_request_duration_seconds_bucket[2m])) by (host, le)) > 3'
      for: 2m
      labels:
        severity: warning
      annotations:
        summary: Nginx latency high (instance {{ $labels.instance }})
        description: "Nginx p99 latency is higher than 3 seconds\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"
