---
- name: Restart service php-fpm
  ansible.builtin.systemd_service:
    name: php-fpm.service
    state: restarted
  ignore_errors: '{{ ansible_check_mode }}'

- name: Restart timer glpi
  ansible.builtin.systemd_service:
    name: glpi.timer
    state: restarted
  ignore_errors: '{{ ansible_check_mode }}'
...
