---
node_exporter_version: 1.8.2
node_exporter_download_url: "https://github.com/prometheus/node_exporter\
  /releases/download/v{{ node_exporter_version }}\
  /node_exporter-{{ node_exporter_version }}.linux-amd64.tar.gz"

node_exporter_cert: '{{ undef(hint="node_exporter_cert") }}'
node_exporter_certfile: /etc/node_exporter/server.crt
node_exporter_key: '{{ undef(hint="node_exporter_key") }}'
node_exporter_keyfile: /etc/node_exporter/server.key

node_exporter_listen: ['0.0.0.0:9100']

node_exporter_user: metrics
node_exporter_password_hash: '{{ undef(hint="node_exporter_password_hash") }}'
...
