{
 "title": "Nginx VTS",
 "description": "nginx_vts_status grafana graph",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "Instance",
    "query": "label_values(nginx_vts_server_bytes_total, instance)"
   },
   {
    "name": "host",
    "label": "Host",
    "query": "label_values(nginx_vts_server_requests_total{instance=~\"$instance\"}, host)"
   },
   {
    "name": "upstream",
    "label": "Upstream",
    "query": "label_values(nginx_vts_upstream_requests_total{instance=~\"$instance\"}, upstream)"
   },
   {
    "name": "backend",
    "label": "Backend",
    "query": "label_values(nginx_vts_upstream_requests_total{instance=~\"$instance\", upstream=~\"$upstream\"}, backend)"
   }
  ]
 },
 "panels": [
  {
   "title": "Server Connections",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(nginx_vts_main_connections{instance=~\"$instance\", status=~\"active|writing|reading|waiting\"}) by (status)",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "active",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(nginx_vts_main_connections{status=\"active\"}[1m]))"
    }
   ]
  },
  {
   "title": "writing",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(nginx_vts_main_connections{status=\"writing\"}[1m]))"
    }
   ]
  },
  {
   "title": "read",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(nginx_vts_main_connections{status=\"reading\"}[1m]))"
    }
   ]
  },
  {
   "title": "waiting",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(nginx_vts_main_connections{status=\"waiting\"}[1m]))"
    }
   ]
  },
  {
   "title": "Server Requests",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(nginx_vts_server_requests_total{instance=~\"$instance\", host=~\"$host\", code!=\"total\"}[5m])) by (code)",
     "legendFormat": "{{ code }}"
    }
   ]
  },
  {
   "title": "Backend Requests",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(nginx_vts_upstream_requests_total{backend=~\"$backend\", instance=~\"$instance\", code!=\"total\"} [1m])) by (code)",
     "legendFormat": "{{code}}"
    }
   ]
  },
  {
   "title": "Upstream Requests",
   "type": "timeseries",
   "description": "This one is providing aggregated error codes, but it's still possible to graph these per upstream.",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(nginx_vts_upstream_requests_total{instance=~\"$instance\", upstream=~\"$upstream\", backend=~\"$backend\", code!=\"total\"}[1m])) by (code)",
     "legendFormat": "{{ code }}"
    }
   ]
  },
  {
   "title": "Server Bytes",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(rate(nginx_vts_server_bytes_total{instance=~\"$instance\", host=~\"$host\"}[5m])) by (direction)",
     "legendFormat": "{{ direction }}"
    }
   ]
  },
  {
   "title": "Upstream Bytes",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(nginx_vts_upstream_bytes_total{instance=~\"$instance\", upstream=~\"$upstream\", backend=~\"$backend\"}[5m])) by (direction)",
     "legendFormat": "{{ direction }}"
    }
   ]
  },
  {
   "title": "Upstream Backend Response",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(nginx_vts_upstream_response_seconds{instance=~\"$instance\", upstream=~\"$upstream\", backend=~\"$backend\"}) by (backend)",
     "legendFormat": "{{ backend }}"
    }
   ]
  }
 ]
}