{
 "title": "Summary",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "job",
    "label": "Job",
    "query": {
     "query": "label_values(node_exporter_build_info,job)"
    }
   },
   {
    "name": "group",
    "label": "Group",
    "query": {
     "query": "label_values(node_exporter_build_info{job=~\"$job\"},group)"
    }
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(node_exporter_build_info{job=~\"$job\", group=~\"$group\"},instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "CPU Load",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum without(cpu, mode)(rate(node_cpu_seconds_total{\n    job=~\"$job\", group=~\"$group\", instance=~\"$instance\", mode!~\"idle|iowait\"\n}[$__rate_interval]))\n/\ncount without(cpu, mode)(count without(mode)(node_cpu_seconds_total{\n    job=~\"$job\", group=~\"$group\", instance=~\"$instance\"\n}))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "1 - (\n    node_memory_MemFree_bytes{job=~\"$job\", group=~\"$group\", instance=~\"$instance\"}\n    + \n    node_memory_Cached_bytes{job=~\"$job\", group=~\"$group\", instance=~\"$instance\"}\n    + \n    node_memory_SReclaimable_bytes{job=~\"$job\", group=~\"$group\", instance=~\"$instance\"}\n)/node_memory_MemTotal_bytes{job=~\"$job\", group=~\"$group\", instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Disk Bytes Read",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "rate(\n    node_disk_read_bytes_total{\n        job=~\"$job\", group=~\"$group\", instance=~\"$instance\"\n    }[$__rate_interval]\n)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Disk Bytes Written",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "rate(\n    node_disk_written_bytes_total{\n        job=~\"$job\", group=~\"$group\", instance=~\"$instance\"\n    }[$__rate_interval]\n)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Network Bits In",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "8*sum without(device)(\n    rate(\n        node_network_receive_bytes_total{\n            job=~\"$job\", group=~\"$group\", instance=~\"$instance\"\n        }[$__rate_interval]\n    )\n)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Network Bits Out",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "8*sum without(device)(\n    rate(\n        node_network_transmit_bytes_total{\n            job=~\"$job\", group=~\"$group\", instance=~\"$instance\"\n        }[$__rate_interval]\n    )\n)",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}