---
- name: Update user passwords file {{ passwd.name }}
  community.general.htpasswd:
    path: /etc/angie/{{ passwd.name }}.htpasswd
    create: true
    name: '{{ item.name }}'
    password: '{{ item.password }}'
    hash_scheme: bcrypt
    owner: angie
    group: angie
    mode: '0400'
  loop: '{{ passwd.records }}'
  no_log: '{{ not debug }}'
...
