---
- name: Import install tasks
  ansible.builtin.import_tasks: install.yml

- name: Import certs tasks
  ansible.builtin.import_tasks: certs.yml

- name: Import config tasks
  ansible.builtin.import_tasks: config.yml

- name: Enable and start service alertmanager
  ansible.builtin.systemd:
    name: alertmanager.service
    enabled: true
    daemon_reload: true
    state: started
  ignore_errors: '{{ ansible_check_mode }}'
...
