---
- name: Add opensearch repo
  ansible.builtin.yum_repository:
    name: opensearch-2.x
    description: OpenSearch 2.x
    baseurl: https://artifacts.opensearch.org/releases/bundle/opensearch/2.x/yum
    gpgcheck: true
    enabled: true
    gpgkey: https://artifacts.opensearch.org/publickeys/opensearch.pgp
    state: present

- name: Install opensearch
  ansible.builtin.dnf:
    name: opensearch-{{ opensearch_version }}
    state: present

- name: Install opensearch prometheus plugin
  ansible.builtin.command: >-
    /usr/share/opensearch/bin/opensearch-plugin
    install --batch
    {{ opensearch_prometheus_download_url }}
  args:
    creates: "/usr/share/opensearch/plugins/prometheus-exporter\
      /plugin-descriptor.properties"
...
