---
- name: Import install tasks
  ansible.builtin.import_tasks: install.yml

- name: Import certs tasks
  ansible.builtin.import_tasks: certs.yml

- name: Import config tasks
  ansible.builtin.import_tasks: config.yml

- name: Updating sysctl vm.max_map_count
  ansible.posix.sysctl:
    name: vm.max_map_count
    value: 262144
    reload: true
    state: present

- name: Enable and start service opensearch
  ansible.builtin.systemd_service:
    name: opensearch.service
    enabled: true
    state: started
  ignore_errors: '{{ ansible_check_mode }}'
...
