---
- name: Configure config directory path
  ansible.builtin.template:
    src: downstream.php
    dest: '{{ glpi_dir }}/inc/downstream.php'
    owner: root
    group: root
    mode: '0644'

- name: Configure var and log directory path
  ansible.builtin.template:
    src: local_define.php
    dest: '{{ glpi_config_dir }}/local_define.php'
    owner: root
    group: root
    mode: '0644'

- name: Update database connection certs
  ansible.builtin.import_tasks: certs.yml

- name: Create database
  ansible.builtin.import_tasks: database.yml
...
