---
- name: Install a modularity php appstream with 8.2 stream
  ansible.builtin.dnf:
    name: '@php:8.2'
    state: present

- name: Install php and required php modules
  ansible.builtin.dnf:
    name:
      - php
      - php-common
      - php-gd
      - php-intl
      - php-ldap
      - php-mysqlnd
      - php-opcache
      - php-pecl-zip
      - php-xml
    state: present

- name: Configure php session module
  ansible.builtin.template:
    src: php-session.ini
    dest: /etc/php.d/20-session.ini
    owner: root
    group: root
    mode: '0644'

- name: Create angie.service.d directory
  ansible.builtin.file:
    path: /etc/systemd/system/angie.service.d
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: Configure angie service dependency
  ansible.builtin.template:
    src: php-fpm.conf
    dest: /etc/systemd/system/angie.service.d/php-fpm.conf
    owner: root
    group: root
    mode: '0644'

- name: Remove php apache configuration (pool www)
  ansible.builtin.file:
    path: /etc/php/php-fpm.d/www.conf
    state: absent
  notify: Restart service php-fpm

- name: Configure glpi php fpm pool
  ansible.builtin.template:
    src: glpi-fpm-pool.conf
    dest: /etc/php-fpm.d/glpi.conf
    owner: root
    group: root
    mode: '0644'
  notify: Restart service php-fpm

- name: Enable and start service php-fpm
  ansible.builtin.systemd_service:
    name: php-fpm.service
    daemon_reload: true
    enabled: true
    state: started
  ignore_errors: '{{ ansible_check_mode }}'
...
