---
- name: Start services backup
  ansible.builtin.systemd_service:
    name: '{{ item }}.service'
    state: started
  loop: '{{ backup_start_services }}'
  ignore_errors: '{{ ansible_check_mode }}'
...
