---
- name: Restart timer backup mariadb
  ansible.builtin.systemd_service:
    name: backup-mariadb-{{ backup_mariadb_name }}.timer
    state: restarted
  ignore_errors: '{{ ansible_check_mode }}'
...
