---
- name: Update prometheus CA certificate file
  ansible.builtin.copy:
    content: '{{ prometheus_ca }}'
    dest: '{{ prometheus_cafile }}'
    owner: root
    group: root
    mode: '0644'
  diff: false
  notify: Reload service prometheus

- name: Update prometheus certificate file
  ansible.builtin.copy:
    content: '{{ prometheus_cert }}'
    dest: '{{ prometheus_certfile }}'
    owner: root
    group: root
    mode: '0644'
  diff: false
  notify: Reload service prometheus

- name: Update prometheus key file
  ansible.builtin.copy:
    content: '{{ prometheus_key }}'
    dest: '{{ prometheus_keyfile }}'
    owner: prometheus
    group: prometheus
    mode: '0640'
  no_log: '{{ not debug }}'
  notify: Reload service prometheus
...
