---
- name: Update prometheus systemd service
  ansible.builtin.template:
    src: prometheus.service
    dest: /etc/systemd/system/prometheus.service
    lstrip_blocks: true
    owner: root
    group: root
    mode: '0644'
  notify: Restart service prometheus

- name: Update prometheus config
  ansible.builtin.template:
    src: prometheus.yml.j2
    dest: '{{ prometheus_config }}'
    lstrip_blocks: true
    owner: root
    group: root
    mode: '0644'
  notify: Reload service prometheus

- name: Update prometheus web config
  ansible.builtin.template:
    src: web.yml.j2
    dest: '{{ prometheus_web_config }}'
    owner: prometheus
    group: prometheus
    mode: '0640'
  no_log: true
  notify: Reload service prometheus

- name: Create rules directory
  ansible.builtin.file:
    path: '{{ prometheus_rules_dir }}'
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: Update prometheus alert rules
  ansible.builtin.copy:
    src: 'rules/{{ item }}'
    dest: '{{ prometheus_rules_dir }}/{{ item }}'
    owner: root
    group: root
    mode: '0644'
  loop: '{{
      query(
        "ansible.builtin.fileglob",
        "/".join((role_path, "files/rules/*.yml"))
      ) | map("ansible.builtin.basename")
    }}'  # noqa: jinja[spacing]
  notify: Reload service prometheus
...
