---
- name: Update prometheus password file
  ansible.builtin.copy:
    content: '{{ item.password }}'
    dest: '{{ item.file }}'
    owner: prometheus
    group: prometheus
    mode: '0640'
  loop: '{{ prometheus_passwords }}'
  no_log: '{{ not debug }}'
  notify: Reload prometheus service
...
