---
ip: '192.168.57.10'

ssh_key_users: [root]
ssh_known_hosts_list:
  - '{{ hostvars["primary"].ip }}'
  - '{{ hostvars["replica"].ip }}'
ssh_known_hosts_users: [root]

backup_nfs_src: /mnt/nfs/glpi

nfs_automount_mount: '{{ backup_nfs_src }}'
nfs_automount_host: '{{ hostvars["nfs"].ip }}'
nfs_automount_path: /glpi

backup_mariadb_name: primary
backup_mariadb_host: '{{ hostvars["primary"].ip }}'

restic_repo_password: '{{ lookup("ansible.builtin.password",
  "secrets/restic_password.txt", length=26) }}'
restic_backup_password: '{{ restic_repo_password }}'
restic_backup_name: nfs-glpi
restic_backup_sources: ['{{ backup_nfs_src }}']
...
