---
ip: '192.168.57.18'
ip_external: '192.168.56.18'

firewalld_override:
  public:
    add_ports: ['{{ angie_metrics_port }}/tcp']
    add_services: [http, https]
  dmz:
    interfaces: [eth2]
    add_services: [http, https]
    remove_services: [ssh]

rsyslog_rules_add: [nginx]

angie_sites: [http_to_https, frontend, metrics]
angie_http_to_https_listen: ['{{ ip_external }}:80']
angie_frontend_listen: ['{{ ip_external }}:443']
angie_frontend_upstreams: '{{ glpi_servers }}'
angie_frontend_server_name: '{{ glpi_server_name }}'

tls_gen_cert_san:
  - 'DNS:{{ glpi_server_name }}'
  - 'DNS:{{ inventory_hostname_short }}.{{ tls_gen_cert_domain }}'
  - 'DNS:localhost'
  - 'IP:{{ ip }}'
  - 'IP:{{ ip_external }}'
  - 'IP:127.0.0.1'
...
