---
ip: '192.168.57.17'

firewalld_override:
  public:
    add_ports: ['9093/tcp']
    add_services: [prometheus, grafana]

prometheus_ca: '{{ tls_ca }}'
prometheus_cert: '{{ tls_full }}'
prometheus_key: '{{ tls_key }}'
prometheus_user: prometheus
prometheus_passwordfile: /etc/prometheus/prometheus.passwd
prometheus_metrics_passwordfile: /etc/prometheus/metrics.passwd
prometheus_passwords:
  - file: '{{ prometheus_passwordfile }}'
    password: '{{ lookup("ansible.builtin.password",
      "secrets/prometheus_password.txt", length=26) }}'
  - file: '{{ prometheus_metrics_passwordfile }}'
    password: '{{ metrics_password }}'
prometheus_password: '{{ lookup("ansible.builtin.password",
  "secrets/prometheus_password.txt", length=26) }}'
prometheus_password_hash: '{{ lookup("ansible.builtin.password",
  "secrets/prometheus_password.txt", length=26, encrypt="bcrypt") }}'

prometheus_listen: ['{{ ip }}:9090']
prometheus_jobs:
  prometheus:
    hosts: ['{{ inventory_hostname }}']
    port: 9090
    username: '{{ prometheus_user }}'
    password_file: '{{ prometheus_password_file }}'
  node:
    hosts: '{{ groups["all"] }}'
    port: 9100
    username: '{{ metrics_user }}'
    password_file: '{{ prometheus_metrics_passwordfile }}'
  nginx:
    hosts: '{{ groups["backend"] + ["frontend"] }}'
    port: '{{ angie_metrics_port }}'
    username: '{{ metrics_user }}'
    password_file: '{{ prometheus_metrics_passwordfile }}'
  opensearch:
    hosts: ['logs']
    port: 9200
    username: '{{ metrics_user }}'
    password_file: '{{ prometheus_metrics_passwordfile }}'
    metrics_path: /_prometheus/metrics
  mysql:
    hosts: '{{ groups["mariadb"] }}'
    port: 9104
    username: '{{ metrics_user }}'
    password_file: '{{ prometheus_metrics_passwordfile }}'

grafana_cert: '{{ tls_full }}'
grafana_key: '{{ tls_key }}'
grafana_admin_user: admin
grafana_admin_password: '{{ lookup("ansible.builtin.password",
  "secrets/grafana_password.txt", length=26) }}'
grafana_db_host: '{{ hostvars["primary"].ip }}'
grafana_db_ca: '{{ tls_ca }}'
grafana_db_cert: '{{ tls_cert }}'
grafana_db_key: '{{ tls_key }}'
grafana_ds_prometheus_uid: adz4zn96lcqv4f
grafana_ds_prometheus_url: https://{{ ip }}:9090
grafana_ds_prometheus_ca: '{{ tls_ca }}'
grafana_ds_prometheus_password: '{{ prometheus_password }}'
grafana_dashboards_ds_uid: '{{ grafana_ds_prometheus_uid }}'
...
