---
ip: '192.168.57.13'

firewalld_override:
  public:
    add_services: [nfs]

nfs_server_subdirs:
  glpi:
    owner: '{{ glpi_uid }}'
    group: '{{ glpi_gid }}'
    mode: '0755'
nfs_exports_opts: rw,sync,insecure,no_subtree_check,no_root_squash
nfs_exports_clients: >
  {{ hostvars["backend1"].ip }}
  {{ hostvars["backend2"].ip }}
nfs_server_exports_content: |
  /glpi -{{ nfs_exports_opts }} {{ nfs_exports_clients }}
...
