---
ip: '192.168.57.11'

mariadb_config_override:
  server_id: 1
  gtid_domain_id: 1

mariadb_users_remove_anonymous: true

mariadb_users_list:
  - name: '{{ mariadb_replication_user }}'
    host: '{{ hostvars["replica"].ip }}'
    password: '{{ mariadb_replication_password }}'
    priv:
      '*.*': REPLICATION REPLICA
  - name: '{{ glpi_db_user }}'
    password: '{{ glpi_db_password }}'
    priv:
      'glpi.*': ALL
    resource_limits:
      MAX_USER_CONNECTIONS: 3
  - name: '{{ mariadb_exporter_user }}'
    host: localhost
    password: '{{ mariadb_exporter_password }}'
    priv:
      '*.*': PROCESS,BINLOG MONITOR,SELECT
    resource_limits:
      MAX_USER_CONNECTIONS: 3

mariadb_databases_list: ['{{ glpi_db_name }}']

mariadb_restore_run: '{{ mariadb_status.status.ActiveState == "inactive" and
  hostvars["replica"].mariadb_status.status.ActiveState == "active" }}'
mariadb_restore_src_host: '{{ hostvars["replica"].ip }}'
mariadb_restore_dst_host: '{{ ip }}'
...
