---
ip: '192.168.57.11'

mariadb_config_override:
  server_id: 1
  gtid_domain_id: 1
  bind_address: '127.0.0.1,{{ ip }}'
  ssl_ca: '{{ mariadb_tls_cafile }}'
  ssl_cert: '{{ mariadb_tls_certfile }}'
  ssl_key: '{{ mariadb_tls_keyfile }}'

mariadb_users_remove_anonymous: true

mariadb_users_list:
  - name: '{{ mariadb_replication_user }}'
    host: '{{ hostvars["replica"].ip }}'
    password: '{{ mariadb_replication_password }}'
    priv: '*.*:REPLICATION REPLICA'
    tls_requires:
      x509:
  - name: '{{ glpi_db_user }}'
    password: '{{ glpi_db_password }}'
    priv: '{{ glpi_db_name }}.*:ALL'
  - name: '{{ grafana_db_user }}'
    password: '{{ grafana_db_password }}'
    priv: '{{ grafana_db_name }}.*:ALL'
    tls_requires:
      x509:
  - name: '{{ mariadb_exporter_user }}'
    host: '127.0.0.1'
    password: '{{ mariadb_exporter_password }}'
    priv: '*.*:PROCESS,BINLOG MONITOR,SELECT'
    resource_limits:
      MAX_USER_CONNECTIONS: 3
    tls_requires:
      x509:

mariadb_databases_list: ['{{ glpi_db_name }}', '{{ grafana_db_name }}' ]

mariadb_restore_run: '{{ mariadb_status.status.ActiveState == "inactive" and
  hostvars["replica"].mariadb_status.status.ActiveState == "active" }}'
mariadb_restore_src_host: '{{ hostvars["replica"].ip }}'
mariadb_restore_dst_host: '{{ ip }}'
...
