---
ip: '192.168.57.12'

mariadb_config_override:
  server_id: 2
  gtid_domain_id: 1
  read_only: true

mariadb_replica_params:
  primary_host: '{{ hostvars["primary"].ip }}'
  primary_user: '{{ mariadb_replication_user }}'
  primary_password: '{{ mariadb_replication_password }}'

mariadb_restore_run: '{{ mariadb_status.status.ActiveState == "inactive" and
  hostvars["primary"].mariadb_status.status.ActiveState == "active" }}'
mariadb_restore_src_host: '{{ hostvars["primary"].ip }}'
mariadb_restore_dst_host: '{{ ip }}'
...
