---
- name: Import install tasks
  ansible.builtin.import_tasks: install.yml

- name: Import certs tasks
  ansible.builtin.import_tasks: certs.yml

- name: Import config tasks
  ansible.builtin.import_tasks: config.yml

- name: Enable and start service mysqld_exporter
  ansible.builtin.systemd:
    name: mysqld_exporter.service
    enabled: true
    daemon_reload: true
    state: started
  when: not ansible_check_mode
...
