---
prometheus_version: '3.1.0'
prometheus_download_url: "https://github.com/prometheus/prometheus/releases\
  /download/v{{ prometheus_version }}\
  /prometheus-{{ prometheus_version }}.linux-amd64.tar.gz"

prometheus_ca: '{{ undef(hint="prometheus_ca") }}'
prometheus_cafile: /etc/prometheus/ca.crt
prometheus_cert: '{{ undef(hint="prometheus_cert") }}'
prometheus_certfile: /etc/prometheus/server.crt
prometheus_key: '{{ undef(hint="prometheus_key") }}'
prometheus_keyfile: /etc/prometheus/server.key

prometheus_user: prometheus
prometheus_password_file: /etc/prometheus/prometheus.passwd
prometheus_password_hash: '{{ undef(hint="prometheus_password_hash") }}'
prometheus_metrics_passwordfile: /etc/prometheus/metrics.passwd

prometheus_retention_time: 7d
prometheus_retention_size: 2GB

prometheus_listen: ['127.0.0.1:9090']
prometheus_jobs:
  prometheus:
    hosts: ['{{ inventory_hostname }}']
    port: 9090
    username: '{{ prometheus_user }}'
    password_file: '{{ prometheus_password_file }}'
prometheus_passwords:
  - file: '{{ prometheus_password_file }}'
    password: '{{ undef(hint="prometheus_password") }}'
...
